#!/usr/bin/env python3
"""
Build Script - Converts markdown content to static HTML pages
Usage: python build.py

This script:
1. Scans content/works/ for .md files
2. Parses YAML frontmatter for metadata
3. Converts markdown to HTML
4. Generates content/works.json index
5. Outputs HTML article pages to works/
"""

import os
import json
import re
from datetime import datetime
from pathlib import Path

import yaml
import pypandoc

# Configuration
CONTENT_DIR = Path("content/works")
OUTPUT_DIR = Path("works")
INDEX_FILE = Path("content/works.json")

# Prism.js Theme - Change this to switch syntax highlighting theme
# Options: prism, prism-dark, prism-funky, prism-okaidia, prism-twilight, 
#          prism-coy, prism-solarizedlight, prism-tomorrow, prism-darcula
PRISM_THEME = "prism-darcula"

# Article HTML template
ARTICLE_TEMPLATE = """<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{subtitle}">
  <title>{title} - Florian Hunecke</title>
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
  <!-- Prism.js for syntax highlighting -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism-themes/1.9.0/{prism_theme}.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/line-numbers/prism-line-numbers.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/toolbar/prism-toolbar.min.css">
  <link rel="stylesheet" href="/css/style.css">
  <script src="/js/theme.js" defer></script>
  <script src="/js/toc.js" defer></script>
  <!-- MathJax for LaTeX math rendering -->
  <script>
    MathJax = {{
      tex: {{
        inlineMath: [['$', '$'], ['\\\\(', '\\\\)']],
        displayMath: [['$$', '$$'], ['\\\\[', '\\\\]']]
      }},
      svg: {{
        fontCache: 'global'
      }}
    }};
  </script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
  <!-- Prism.js scripts -->
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/prism.min.js" defer></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/autoloader/prism-autoloader.min.js" defer></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/line-numbers/prism-line-numbers.min.js" defer></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/toolbar/prism-toolbar.min.js" defer></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js" defer></script>
  <script src="/js/code.js" defer></script>
</head>
<body>
  <!-- Header -->
  <header class="header">
    <div class="header__container">
      <a href="/" class="header__logo">FH</a>
      <nav class="header__nav">
        <button class="header__burger" aria-label="Toggle menu">
          <span></span>
          <span></span>
          <span></span>
        </button>
        <ul class="header__nav-links">
          <li><a href="/" class="header__nav-link">About</a></li>
          <li><a href="/cv.html" class="header__nav-link">CV</a></li>
          <li><a href="/works.html" class="header__nav-link active">Works</a></li>
        </ul>
        <button class="theme-toggle" aria-label="Toggle dark mode">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"/>
          </svg>
        </button>
      </nav>
    </div>
  </header>

  <!-- Main Content -->
  <main class="main">
    <div class="container">
      <article class="article">
        <div class="article__main">
          <header class="article__header">
            <span class="article__type">{type}</span>
            <h1 class="article__title">{title}</h1>
            <div class="article__meta">
              <span>{date}</span>
              <span>{reading_time} min read</span>
            </div>
            <div class="article__tags">
              {tags_html}
            </div>
            {external_links_html}
          </header>
          <div class="article__content">
            {content}
          </div>
        </div>
        <aside class="article__toc">
          <p class="article__toc-title">On this page</p>
          <ul class="article__toc-list">
            <!-- TOC is generated by JS -->
          </ul>
        </aside>
      </article>
    </div>
  </main>

  <!-- Footer -->
  <footer class="footer">
    <div class="footer__container">
      <p class="footer__copyright">© 2024 Florian Hunecke</p>
      <div class="footer__links">
        <a href="https://github.com/MrStrenggeheim" class="footer__link" aria-label="GitHub" target="_blank" rel="noopener">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
          </svg>
        </a>
        <a href="https://linkedin.com/in/florian-hunecke" class="footer__link" aria-label="LinkedIn" target="_blank" rel="noopener">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
            <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
          </svg>
        </a>
      </div>
    </div>
  </footer>
</body>
</html>
"""


def parse_frontmatter(content: str) -> tuple[dict, str]:
    """Parse YAML frontmatter from markdown content."""
    if not content.startswith("---"):
        return {}, content
    
    parts = content.split("---", 2)
    if len(parts) < 3:
        return {}, content
    
    try:
        frontmatter = yaml.safe_load(parts[1])
        body = parts[2].strip()
        return frontmatter or {}, body
    except yaml.YAMLError:
        return {}, content


def calculate_reading_time(content: str) -> int:
    """Calculate estimated reading time in minutes."""
    words = len(content.split())
    return max(1, round(words / 200))


def slugify(text: str) -> str:
    """Convert text to URL-safe slug."""
    text = text.lower()
    text = re.sub(r'[^a-z0-9]+', '-', text)
    return text.strip('-')


def format_date(date_obj) -> str:
    """Format date object to readable string."""
    if isinstance(date_obj, datetime):
        return date_obj.strftime("%b %d, %Y")
    elif isinstance(date_obj, str):
        try:
            dt = datetime.fromisoformat(date_obj)
            return dt.strftime("%b %d, %Y")
        except:
            return date_obj
    return str(date_obj)


def process_markdown(md_content: str) -> str:
    """Convert markdown to HTML using Pandoc with full extension support.
    
    Enables:
    - GFM (GitHub Flavored Markdown)
    - Fenced divs (::: name :::)
    - Footnotes
    - Math ($$, $)
    - Smart quotes
    
    Post-processes HTML to make code blocks compatible with Prism.js.
    """
    try:
        # Use markdown format with all extensions for maximum compatibility
        html = pypandoc.convert_text(
            md_content,
            'html',
            format='markdown+gfm_auto_identifiers+fenced_divs+footnotes+tex_math_dollars+smart+fenced_code_blocks+fenced_code_attributes',
            extra_args=['--no-highlight', '--mathjax']
        )
        
        # Post-process: Convert Pandoc's code block format to Prism-compatible format
        # Pandoc outputs: <div class="sourceCode"><pre class="python"><code class="sourceCode python">
        # or: <pre class="python">code</pre>
        # Prism expects: <pre><code class="language-python">code</code></pre>
        
        # Pattern 1: Full sourceCode div wrapper (Pandoc default)
        html = re.sub(
            r'<div class="sourceCode[^"]*"[^>]*>\s*<pre[^>]*>\s*<code class="sourceCode\s+(\w+)"[^>]*>(.*?)</code>\s*</pre>\s*</div>',
            r'<pre><code class="language-\1">\2</code></pre>',
            html,
            flags=re.DOTALL
        )
        
        # Pattern 2: Simple pre with class (--no-highlight mode)
        html = re.sub(
            r'<pre class="(\w+)">(.*?)</pre>',
            r'<pre><code class="language-\1">\2</code></pre>',
            html,
            flags=re.DOTALL
        )
        
        # Pattern 3: Pre with code but wrong class format
        html = re.sub(
            r'<pre><code class="sourceCode (\w+)"',
            r'<pre><code class="language-\1"',
            html
        )
        
        return html
    except Exception as e:
        print(f"Pandoc error: {e}")
        return f"<p>Error processing markdown: {e}</p>"


def build_works():
    """Main build function."""
    print("🔨 Building works...")
    
    # Create output directory
    OUTPUT_DIR.mkdir(exist_ok=True)
    
    # Collect all markdown files
    works = []
    
    for type_dir in ["blog", "project", "publication"]:
        type_path = CONTENT_DIR / type_dir
        if not type_path.exists():
            continue
        
        for md_file in type_path.glob("*.md"):
            print(f"  Processing: {md_file}")
            
            # Read and parse
            content = md_file.read_text(encoding="utf-8")
            frontmatter, body = parse_frontmatter(content)
            
            # Extract metadata
            title = frontmatter.get("title", md_file.stem.replace("-", " ").title())
            subtitle = frontmatter.get("subtitle", "")
            date = frontmatter.get("date", datetime.now().isoformat()[:10])
            tags = frontmatter.get("tags", [])
            thumbnail = frontmatter.get("thumbnail", "/assets/thumbnails/default.png")
            work_type = type_dir
            
            # Generate slug and URL
            slug = slugify(title)
            url = f"/works/{slug}.html"
            
            # Calculate reading time
            reading_time = calculate_reading_time(body)
            
            # Convert markdown to HTML
            html_content = process_markdown(body)
            
            # Generate tags HTML (clickable links to works page with tag filter)
            from urllib.parse import quote
            tags_html = "".join([
                f'<a href="/works.html?tag={quote(tag)}" class="article__tag">{tag}</a>'
                for tag in tags
            ])
            
            # Generate external links HTML (optional)
            external_links = frontmatter.get("links", {})
            external_links_html = ""
            if external_links:
                from urllib.parse import urlparse
                links_items = []
                for name, url in external_links.items():
                    # Parse URL to get domain
                    parsed = urlparse(url)
                    domain = parsed.netloc.lower()
                    
                    # SVG icons for known domains
                    github_svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>'
                    linkedin_svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>'
                    youtube_svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg>'
                    link_svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>'
                    
                    # Infer icon from URL domain
                    if "github.com" in domain or "github.io" in domain:
                        icon = github_svg
                    elif "linkedin.com" in domain:
                        icon = linkedin_svg
                    elif "youtube.com" in domain or "youtu.be" in domain:
                        icon = youtube_svg
                    elif "arxiv.org" in domain:
                        icon = '<img src="https://arxiv.org/favicon.ico" class="article__external-icon" alt="">'
                    elif "doi.org" in domain:
                        icon = '<img src="https://www.doi.org/favicon.ico" class="article__external-icon" alt="">'
                    elif "huggingface.co" in domain:
                        icon = '<img src="https://huggingface.co/favicon.ico" class="article__external-icon" alt="">'
                    elif "kaggle.com" in domain:
                        icon = '<img src="https://www.kaggle.com/favicon.ico" class="article__external-icon" alt="">'
                    elif domain:
                        # Use Google's favicon service as fallback
                        icon = f'<img src="https://www.google.com/s2/favicons?domain={domain}&sz=32" class="article__external-icon" alt="">'
                    else:
                        icon = link_svg
                    
                    links_items.append(f'<a href="{url}" class="article__external-link" target="_blank" rel="noopener">{icon} {name}</a>')
                external_links_html = f'<div class="article__external-links">{"".join(links_items)}</div>'
            
            # Generate article HTML
            article_html = ARTICLE_TEMPLATE.format(
                title=title,
                subtitle=subtitle,
                type=work_type,
                date=format_date(date),
                reading_time=reading_time,
                tags_html=tags_html,
                external_links_html=external_links_html,
                content=html_content,
                prism_theme=PRISM_THEME,
            )
            
            # Write article HTML file
            output_path = OUTPUT_DIR / f"{slug}.html"
            output_path.write_text(article_html, encoding="utf-8")
            print(f"  -> Generated: {output_path}")
            
            # Add to index
            works.append({
                "title": title,
                "subtitle": subtitle,
                "date": str(date),
                "type": work_type,
                "tags": tags,
                "thumbnail": thumbnail,
                "url": url,
                "readingTime": reading_time,
            })
    
    # Sort by date descending
    works.sort(key=lambda x: x["date"], reverse=True)
    
    # Write index JSON
    CONTENT_DIR.mkdir(parents=True, exist_ok=True)
    INDEX_FILE.write_text(json.dumps(works, indent=2), encoding="utf-8")
    print(f"📋 Generated index: {INDEX_FILE} ({len(works)} works)")
    
    print("✅ Works build complete!")


# CV HTML Template
CV_TEMPLATE = """<!DOCTYPE html>
<html lang="en" data-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
        content="Curriculum Vitae of Florian Hunecke - Education, Work Experience, and Achievements.">
    <title>CV - Florian Hunecke</title>
    <link rel="icon" type="image/svg+xml" href="/favicon.svg">
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/theme.js" defer></script>
</head>

<body>
    <!-- Header -->
    <header class="header">
        <div class="header__container">
            <a href="/" class="header__logo">FH</a>
            <nav class="header__nav">
                <button class="header__burger" aria-label="Toggle menu">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <ul class="header__nav-links">
                    <li><a href="/" class="header__nav-link">About</a></li>
                    <li><a href="/cv.html" class="header__nav-link active">CV</a></li>
                    <li><a href="/works.html" class="header__nav-link">Works</a></li>
                </ul>
                <button class="theme-toggle" aria-label="Toggle dark mode">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
                    </svg>
                </button>
            </nav>
        </div>
    </header>

    <!-- Main Content -->
    <main class="main">
        <div class="container">
            <section class="cv">
                <div class="cv__header">
                    <p class="page-title">Curriculum Vitae</p>
                </div>

{sections_html}
            </section>
        </div>
    </main>

    <!-- Footer -->
    <footer class="footer">
        <div class="footer__container">
            <p class="footer__copyright">© 2024 Florian Hunecke</p>
            <div class="footer__links">
                <a href="https://github.com/MrStrenggeheim" class="footer__link" aria-label="GitHub" target="_blank"
                    rel="noopener">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                        <path
                            d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                    </svg>
                </a>
                <a href="https://linkedin.com/in/florian-hunecke" class="footer__link" aria-label="LinkedIn"
                    target="_blank" rel="noopener">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                        <path
                            d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
                    </svg>
                </a>
            </div>
        </div>
    </footer>
</body>

</html>
"""


def build_cv():
    """Generate cv.html from content/cv.yaml."""
    print("🔨 Building CV...")
    
    cv_yaml_path = Path("content/cv.yaml")
    if not cv_yaml_path.exists():
        print("  ⚠️ content/cv.yaml not found, skipping CV generation")
        return
    
    cv_data = yaml.safe_load(cv_yaml_path.read_text(encoding="utf-8"))
    
    sections_html = ""
    for section in cv_data.get("sections", []):
        section_title = section.get("title", "")
        entries_html = ""
        
        for entry in section.get("entries", []):
            entry_title = entry.get("title", "")
            subentries = entry.get("subentries", [])
            
            rows_html = ""
            
            # Title row: (location or date) | title
            entry_meta = ""
            if entry.get("location"):
                entry_meta = f'<p class="cv__location">{entry["location"]}</p>'
            elif entry.get("date"):
                entry_meta = f'<p class="cv__date">{entry["date"]}</p>'
            
            rows_html += f'''
                        <div class="cv__entry-row">
                            {entry_meta}
                            <h3 class="cv__title">{entry_title}</h3>
                        </div>'''
            
            # Subtitle rows: (date or location) | subtitle + description/items
            for sub in subentries:
                sub_meta = ""
                if sub.get("date"):
                    sub_meta = f'<p class="cv__date">{sub["date"]}</p>'
                elif sub.get("location"):
                    sub_meta = f'<p class="cv__location">{sub["location"]}</p>'
                
                sub_content = ""
                if sub.get("subtitle"):
                    sub_content += f'<p class="cv__subtitle">{sub["subtitle"]}</p>'
                if sub.get("description"):
                    sub_content += f'<p class="cv__description">{sub["description"]}</p>'
                if sub.get("items"):
                    items_html = ""
                    for item in sub["items"]:
                        if isinstance(item, dict):
                            items_html += f'<li><a href="{item["link"]}">{item["text"]}</a></li>'
                        else:
                            # Convert markdown links [text](url) to HTML
                            import re
                            item_html = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', item)
                            items_html += f'<li>{item_html}</li>'
                    sub_content += f'<ul class="cv__list">{items_html}</ul>'
                
                rows_html += f'''
                        <div class="cv__entry-row">
                            {sub_meta}
                            <div class="cv__content">{sub_content}</div>
                        </div>'''
            
            entries_html += f'''
                    <article class="cv__entry">{rows_html}
                    </article>'''
        
        sections_html += f"""
                <!-- {section_title} -->
                <section class="cv__section">
                    <h2 class="cv__section-title">{section_title}</h2>
{entries_html}                </section>
"""
    
    # Generate final HTML
    cv_html = CV_TEMPLATE.format(sections_html=sections_html)
    
    # Write to cv.html
    output_path = Path("cv.html")
    output_path.write_text(cv_html, encoding="utf-8")
    print(f"  -> Generated: {output_path}")
    print("✅ CV build complete!")


if __name__ == "__main__":
    build_works()
    build_cv()
    print("\n🎉 All builds complete!")

